# Generated by Django 4.1.3 on 2022-12-04 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fake_csv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "separator",
                    models.CharField(
                        choices=[
                            (",", "Comma (,)"),
                            (".", "Point (.)"),
                            (";", "Semicolon (;)"),
                            ("\\t", "Horizontal tab (\\t)"),
                            (":", "Colon (:)"),
                        ],
                        default=",",
                        max_length=15,
                    ),
                ),
                (
                    "string",
                    models.CharField(
                        choices=[
                            ('""', 'Double quotes (")'),
                            ("''", "Single quotes (')"),
                        ],
                        default='""',
                        max_length=10,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(default="Mariia Ivanova", max_length=255),
                ),
                ("phone", models.CharField(default="+48765456234", max_length=14)),
                ("email", models.EmailField(default="kuzka@ukr.net", max_length=254)),
                ("company", models.CharField(default="Apple", max_length=30)),
                (
                    "text",
                    models.TextField(
                        default="doijafghdliughdsfgnsdlfgbitghsifbsldfbgsleitybg"
                    ),
                ),
                ("address", models.CharField(default="Sobieskiego 6", max_length=255)),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2008, 11, 26, 18, 26, 52)
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
