# Generated by Django 4.1.3 on 2022-12-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fake_csv", "0003_schema_modified_alter_schema_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="company",
            field=models.CharField(default="Biedronka", max_length=30),
        ),
        migrations.AlterField(
            model_name="schema",
            name="date",
            field=models.DateField(default=29409275),
        ),
        migrations.AlterField(
            model_name="schema",
            name="email",
            field=models.EmailField(default="devochka@list.ru", max_length=254),
        ),
        migrations.AlterField(
            model_name="schema",
            name="full_name",
            field=models.CharField(default="Denis Egorov", max_length=255),
        ),
        migrations.AlterField(
            model_name="schema",
            name="phone",
            field=models.CharField(default="+79901224533", max_length=14),
        ),
    ]
