# Generated by Django 4.1.3 on 2022-12-04 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fake_csv", "0004_alter_schema_company_alter_schema_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="address",
            field=models.CharField(default="Koroliuka 25", max_length=255),
        ),
        migrations.AlterField(
            model_name="schema",
            name="company",
            field=models.CharField(default="Google", max_length=30),
        ),
        migrations.AlterField(
            model_name="schema",
            name="date",
            field=models.DateField(default=datetime.datetime(2008, 2, 26, 21, 32, 6)),
        ),
        migrations.AlterField(
            model_name="schema",
            name="full_name",
            field=models.CharField(default="Mariia Ivanova", max_length=255),
        ),
        migrations.AlterField(
            model_name="schema",
            name="phone",
            field=models.CharField(default="+89981425565", max_length=14),
        ),
    ]
