# Generated by Django 4.1.3 on 2022-12-04 23:55

from django.db import migrations, models
import fake_csv.functions


class Migration(migrations.Migration):

    dependencies = [
        ("fake_csv", "0005_alter_schema_address_alter_schema_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="address",
            field=models.CharField(
                default=fake_csv.functions.random_address, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="company",
            field=models.CharField(
                default=fake_csv.functions.random_company, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="date",
            field=models.DateField(default=fake_csv.functions.random_date),
        ),
        migrations.AlterField(
            model_name="schema",
            name="email",
            field=models.EmailField(
                default=fake_csv.functions.random_email, max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="full_name",
            field=models.CharField(
                default=fake_csv.functions.random_fullname, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="phone",
            field=models.CharField(
                default=fake_csv.functions.random_phone, max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="text",
            field=models.TextField(default=fake_csv.functions.random_text),
        ),
    ]
