# Generated by Django 4.1.3 on 2022-12-05 17:49

from django.db import migrations, models
import fake_csv.functions


class Migration(migrations.Migration):

    dependencies = [
        ("fake_csv", "0006_alter_schema_address_alter_schema_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schema",
            name="domain",
            field=models.CharField(
                default=fake_csv.functions.random_domain, max_length=16
            ),
        ),
        migrations.AddField(
            model_name="schema",
            name="integer",
            field=models.IntegerField(default=fake_csv.functions.random_int),
        ),
    ]
